[package]
name = "randomizable"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
randomizable_derive = { path = "../randomizable_derive" }
rand = "0.8"
